Add 3.13 compatibility
rnag/dataclass-wizard pull request #129
Opened 2024-10-21 16:24 UTC by benjjs

Package is currently not compatible with Python 3.13 because it uses 2 functions from the `dataclasses` module that were removed from 3.12 to 3.13.

To resolve this problem, I have simply pulled the relevant functions (along with one helper that was also removed) into the package. I've documented which version they were removed in and the original functions in 3.12 that they are copied from.

The only other change is to explicitly pass empty `type_params` to `typing._eval_type()`, as leaving it implicit raises a warning in 3.13. Given that we previously did not supply this argument and the implicit default value was `()`, explicitly passing `()` will not change the behavior.

There is almost certainly some more elegant way to do this that would involve removing the need for these functions in the first place, but my priority here was to add compatibility quickly and without modifying any underlying logic and hence potentially breaking things. If you (the commenter or reviewer) have the more elegant implementation, by all means put it up and let's do that instead!

2024-11-04 00:13 UTC, rnag requested changes

2024-11-04 00:13 UTC, rnag commented on dataclass_wizard/utils/typing_compat.py
> +        return typing._eval_type(base_type, base_globals, _TYPING_LOCALS, type_params=())
@benjjs Minor thing, can you pull this out to the top level? That way we won't need to do a python version check each time `eval_forward_ref` is called. Thanks!

```
if sys.version_info >= (3, 13):
  _eval_type = functools.partial(typing._eval_type, type_params=())
else:
  _eval_type = typing._eval_type
```

2024-11-04 00:13 UTC, rnag commented on dataclass_wizard/utils/compatibility.py
> +def _set_qualname(cls, value):
Good idea, thanks!

2024-11-04 00:13 UTC, rnag commented on dataclass_wizard/serial_json.py
> +from .utils.compatibility import _create_fn, _set_new_attribute
I am wondering if we can come up with a better name for the module. Maybe something like `dataclasses_compat`? I think `compatability` is a bit vague overall.

2024-11-04 00:18 UTC, rnag commented
@benjjs  Thanks so much for creating this PR!

I recently upgraded my laptop to Python 3.13, and I also noticed that Dataclass Wizard breaks on import due to the errors mentioned in the PR. I feel that was my bad on importing hidden functions from (a built in) module, which is a big no-no as I always say 😅 .

Thanks again for your work and effort in creating this PR! I have added some comments, please let me know when you're able to look into the notes I added, and I will merge the bugfix for 3.13 once complete. Have a great day!

2024-11-04 00:21 UTC, rnag commented on dataclass_wizard/utils/typing_compat.py
> +        return typing._eval_type(base_type, base_globals, _TYPING_LOCALS, type_params=())
Follow-up can we please add this to `utils/typing_compat.py` and import/use it instead:

```
# Check if currently running Python 3.8
PY313 = _PY_VERSION == (3, 13)
```

Thanks!

2024-11-04 15:59 UTC, benjjs commented
Thanks for reviewing @rnag ! Addressed the above comments.

2024-11-04 21:42 UTC, rnag commented
Thanks @benjjs ! Everything looks good to go. I'll review/merge later today.

2024-11-05 11:54 UTC, rnag commented on dataclass_wizard/utils/typing_compat.py
> +        return typing._eval_type(base_type, base_globals, _TYPING_LOCALS, type_params=())
> @benjjs Minor thing, can you pull this out to the top level? That way we won't need to do a python version check each time `eval_forward_ref()` is called. Thanks!
> 
> ```
> if sys.version_info >= (3, 13):
>   _eval_type = functools.partial(typing._eval_type, type_params=())
> else:
>   _eval_type = typing._eval_type
> ```

This was not resolved, but its OK, I can do that. Simple fix.

2024-11-05 11:56 UTC, merged

2024-11-05 11:57 UTC, rnag commented
Ok, looks good to go. Thanks! One minor change left, and I will work on the release.

I actually dozed off yesterday night, so I was not able to do it then 😓 . Stay tuned for the release!

2024-11-05 12:28 UTC, rnag commented
@benjjs Done - Thanks for your effort and help on this (also your patience!) 

[v0.26.0](https://pypi.org/project/dataclass-wizard/0.26.0/) is officially live, and adds support for PY 3.13 🎉