feat: allow no key transformations
rnag/dataclass-wizard pull request #94
Opened 2023-08-29 15:11 UTC by cquick01

Allows the ability to define keys in JSON/dataclass that do not undergo transformation.

```python
@dataclass
class MyDataclass(JSONWizard):
    VAR_1: int
    vAr__2: int
    VAr3__: int

    class _(JSONWizard.Meta):
        key_transform_with_dump = "NONE"

data = """{
    "VAR_1": 1,
    "vAr__2": 2,
    "VAr3__": 3
}
"""

foo = MyDataclass.from_json(data)
print("JSON -> Dataclass", foo)
print("Dataclass -> JSON", foo.to_json())
```

prints with no transformations

```
JSON -> Dataclass {
  "VAR_1": 1,
  "vAr__2": 2,
  "VAr3__": 3
}
Dataclass -> JSON {"VAR_1": 1, "vAr__2": 2, "VAr3__": 3}
```

2024-01-30 21:39 UTC, rnag requested changes

2024-01-30 21:42 UTC, rnag commented
Closes #92  - just linking issue directly here.

2024-01-31 14:33 UTC, cquick01 commented on dataclass_wizard/enums.py
> +    NONE = FuncWrapper(str)
That sounds reasonable, I'll push that change shortly. Thanks!

2024-01-31 14:43 UTC, cquick01 commented on dataclass_wizard/enums.py
> +    NONE = FuncWrapper(str)
Tested briefly with the example script in the PR, all seems to be working :+1:

2024-01-31 18:04 UTC, rnag commented on dataclass_wizard/enums.py
> +    NONE = FuncWrapper(str)
LGTM @cquick01 . I kicked off the CI workflow, will take a look and merge / deploy version later today if all seems good.

2024-02-01 14:00 UTC, rnag approved these changes

2024-02-01 14:02 UTC, merged

2024-07-16 20:37 UTC, adamcunnington-mlg commented
@rnag Did this change get reversed? I see that NONE is not allowed :( and this code isn't in main? https://github.com/cquick01/dataclass-wizard/blob/main/dataclass_wizard/enums.py

2024-07-20 00:25 UTC, cquick01 commented
@adamcunnington-mlg I see it in main - https://github.com/rnag/dataclass-wizard/blob/main/dataclass_wizard/enums.py#L32

But I don't think a new tag/release was done

2024-07-20 14:27 UTC, adamcunnington-mlg commented
@rnag please can you make a release?

2024-09-09 20:56 UTC, nathan-beam commented
Bump @rnag - would like this feature. Thanks!

2024-09-18 11:38 UTC, rnag commented
Sorry for the delay -- I just released [v0.23.0](https://pypi.org/project/dataclass-wizard/0.23.0/) with the update to allow no key transformations.

Thanks for your work on this @cquick01 -- I credited you in the [release notes](https://dataclass-wizard.readthedocs.io/en/latest/history.html#id1).

2024-09-18 12:28 UTC, adamcunnington-mlg commented
@rnag thank you for this! Please can you also review, PR, https://github.com/rnag/dataclass-wizard/pull/125/files which address 1 other open bug issue